Repaired a number of problems with the jittyc compiler under linux. The function address on function symbols and the function address on aterms were confused. They now have different names. This problem was recently introduced when adapting the storage structure of aterms.
Three tests still fail under linux (gcc 4.4.4) with the following compilation error that 
I do not understand:

/home/jfg/MCRL2/libraries/data/include/mcrl2/data/set_comprehension.h:25: error: 'class mcrl2::data::set_comprehension' is not a function,
/home/jfg/MCRL2/libraries/data/include/mcrl2/data/set.h:262: error:   conflict with 'mcrl2::data::application mcrl2::data::sort_set::set_comprehension(const mcrl2::data::sort_expression&, const mcrl2::data::data_expression&)'
/home/jfg/MCRL2/libraries/data/include/mcrl2/data/set.h:264: error:   in call to 'set_comprehension'
/home/jfg/MCRL2/libraries/data/include/mcrl2/data/set_comprehension.h: In function 'mcrl2::data::function_symbol_vector mcrl2::data::sort_set::set_generate_functions_code(const mcrl2::data::sort_expression&)':

The tests that still fail are:
        lps_multi_action_test (Failed)
        pbes_constelm_test (Failed)
        data_builder_test (Failed)







git-svn-id: https://svn.win.tue.nl/repos/MCRL2/trunk@11848 21252fe5-60e8-0310-8ff0-c1ae1001594e