Some rather arbitrary changes in the indicated file in the hope that this convinces the virtual studio compiler to compile this code, instead of reporting:
libraries\data\include\mcrl2\data\fourier_motzkin.h(326) : fatal error C1001: An internal error has occurred in the compiler.
INTERNAL COMPILER ERROR in 'C:\PROGRA~2\MICROS~3.0\VC\bin\X86_AM~1\cl.exe'



git-svn-id: https://svn.win.tue.nl/repos/MCRL2/trunk@14993 21252fe5-60e8-0310-8ff0-c1ae1001594e